format_version: v1.0
type: UniqueComponent
attributes: {id: tcpipDns}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: TCPIP_DNS_CLIENT_HEAP_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipDns, value: '568'}
  - type: Integer
    attributes: {id: TCPIP_DNS_CLIENT_MAX_HOSTNAME_LEN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '128'}
- type: ElementPosition
  attributes: {x: '29', y: '60', id: tcpipDns}
