format_version: v1.0
type: UniqueComponent
attributes: {id: tcpipSntp}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: TCPIP_NTP_SERVER}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: time.google.com}
  - type: String
    attributes: {id: TCPIP_NTP_SERVER_MAX_LENGTH}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '30'}
- type: ElementPosition
  attributes: {x: '460', y: '20', id: tcpipSntp}
