format_version: v1.0
type: UniqueComponent
attributes: {id: drvWifiPic32mzw1}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: DRV_WIFI_PIC32MZW1_REQUIRE_BA414E}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiPic32mzw1, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_PIC32MZW1_SUPPORT_WPA3}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiPic32mzw1, value: 'true'}
      - type: User
        attributes: {value: 'false'}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: BA414E_Dependency}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: DirectCapability
    attributes: {id: libdrvPic32mzw1Mac}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: tcpipNetConfig_0}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: NETCONFIG_MAC_Dependency}
- type: ElementPosition
  attributes: {x: '309', y: '184', id: drvWifiPic32mzw1}
