format_version: v1.0
type: UniqueComponent
attributes: {id: tcpipCmd}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: TCPIP_STACK_COMMANDS_ICMP_ECHO_REQUEST_BUFF_SIZE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: TCPIP_STACK_COMMANDS_ICMP_ECHO_REQUEST_DATA_SIZE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: TCPIP_STACK_COMMANDS_STORAGE_ENABLE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
- type: ElementPosition
  attributes: {x: '700', y: '20', id: tcpipCmd}
