format_version: v1.0
type: UniqueComponent
attributes: {id: adchs}
children:
- type: Symbols
  children:
  - type: KeyValueSet
    attributes: {id: ADCCON1__SELRES}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: KeyValueSet
    attributes: {id: ADCCON1__STRGSRC}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: '5'}
  - type: Long
    attributes: {id: ADCCON2__ADCDIV}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Long
    attributes: {id: ADCCON2__SAMC}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: KeyValueSet
    attributes: {id: ADCCON3__ADCSEL}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0'}
  - type: Boolean
    attributes: {id: ADCCSS1__CSS1}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: ADCCSS1__CSS10}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: ADCCSS1__CSS11}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: ADCCSS1__CSS12}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: ADCCSS1__CSS13}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: ADCCSS1__CSS14}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: ADCCSS1__CSS15}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: ADCCSS1__CSS16}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: ADCCSS1__CSS17}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: ADCCSS1__CSS18}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: ADCCSS1__CSS19}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: ADCCSS1__CSS2}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: ADCCSS1__CSS3}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: ADCCSS1__CSS4}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: ADCCSS1__CSS5}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: ADCCSS1__CSS6}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: ADCCSS1__CSS7}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: ADCCSS1__CSS8}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: ADCCSS1__CSS9}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: ADCGIRQEN1__AGIEN15}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: ADCHS_7_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: String
    attributes: {id: ADCHS_7_NAME}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Hex
    attributes: {id: ADCHS_ADCCON1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '6684672'}
  - type: Hex
    attributes: {id: ADCHS_ADCCON2}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '131073'}
  - type: Hex
    attributes: {id: ADCHS_ADCCON3}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '16777216'}
  - type: Hex
    attributes: {id: ADCHS_ADCCSS1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '32768'}
  - type: Hex
    attributes: {id: ADCHS_ADCGIRQEN1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '32768'}
  - type: Hex
    attributes: {id: ADCHS_ADCIMCON1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '0'}
  - type: Hex
    attributes: {id: ADCHS_ADCTRG1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '0'}
  - type: Hex
    attributes: {id: ADCHS_ADCTRG2}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '0'}
  - type: Comment
    attributes: {id: ADCHS_CLASS2_INPUT1}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Comment
    attributes: {id: ADCHS_CLASS2_INPUT2}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Comment
    attributes: {id: ADCHS_CLASS2_INPUT3}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Comment
    attributes: {id: ADCHS_CLASS2_INPUT4}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Comment
    attributes: {id: ADCHS_CLASS2_INPUT5}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Comment
    attributes: {id: ADCHS_CLASS2_INPUT6}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Comment
    attributes: {id: ADCHS_CLASS2_INPUT7}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Comment
    attributes: {id: ADCHS_CLASS3_INPUTS}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Float
    attributes: {id: ADCHS_CONV_RATE0}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '1562.5'}
  - type: Float
    attributes: {id: ADCHS_CONV_RATE7}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '1470.5883'}
  - type: String
    attributes: {id: ADCHS_DMA_STATUS_REG}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: ADCDMAST}
  - type: Hex
    attributes: {id: ADCHS_IEC0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '33554432'}
  - type: Boolean
    attributes: {id: ADCHS_INTERRUPT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: 'true'}
  - type: Float
    attributes: {id: ADCHS_TADC0}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '40.0'}
  - type: Float
    attributes: {id: ADCHS_TADC7}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '40.0'}
  - type: Float
    attributes: {id: ADCHS_TCLK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '10.0'}
  - type: Float
    attributes: {id: ADCHS_TQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: '20.0'}
  - type: Boolean
    attributes: {id: ADCIMCON1__DIFF15}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: ADCIMCON1__SIGN15}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: KeyValueSet
    attributes: {id: ADCTRG1__TRGSRC1}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: KeyValueSet
    attributes: {id: ADCTRG1__TRGSRC2}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: KeyValueSet
    attributes: {id: ADCTRG1__TRGSRC3}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: KeyValueSet
    attributes: {id: ADCTRG2__TRGSRC4}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: KeyValueSet
    attributes: {id: ADCTRG2__TRGSRC5}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: KeyValueSet
    attributes: {id: ADCTRG2__TRGSRC6}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: KeyValueSet
    attributes: {id: ADCTRG2__TRGSRC7}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: String
    attributes: {id: ADC_CALLBACK_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: ADCHS_CallbackRegister}
  - type: String
    attributes: {id: ADC_CH_PHASE_U}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: ADCHS_CH0}
  - type: String
    attributes: {id: ADC_CH_PHASE_V}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: ADCHS_CH4}
  - type: String
    attributes: {id: ADC_CH_POT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: ADCHS_CH15}
  - type: String
    attributes: {id: ADC_CH_VDC_BUS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: ADCHS_CH10}
  - type: String
    attributes: {id: ADC_GET_RESULT_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: ADCHS_ChannelResultGet}
  - type: String
    attributes: {id: ADC_IS_RESULT_READY_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: ADCHS_ChannelResultIsReady}
  - type: String
    attributes: {id: ADC_START_CONV_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: ADCHS_ChannelConversionStart}
  - type: Boolean
    attributes: {id: AN15}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: String
    attributes: {id: INTERRUPT_ADC_RESULT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adchs, value: INT_SOURCE_ADC_DATA0}
- type: ElementPosition
  attributes: {x: '285', y: '201', id: adchs}
