format_version: v1.0
type: GeneratorComponent
attributes: {id: atecc608a}
children:
- type: Instances
  children:
  - type: InstanceComponent
    attributes: {instance: '0', id: atecc608a}
    children:
    - type: Symbols
      children:
      - type: String
        attributes: {id: DRV_I2C_PLIB}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: atecc608a_0, value: I2C2}
      - type: Hex
        attributes: {id: I2C_ADDR}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: atecc608a_0, value: '106'}
      - type: String
        attributes: {id: INTERFACE}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: atecc608a_0, value: ATCA_I2C_IFACE}
      - type: KeyValueSet
        attributes: {id: PART_TYPE}
        children:
        - type: Values
          children:
          - type: User
            attributes: {value: '1'}
    - type: Attachments
      children:
      - type: MultiCapability
        attributes: {id: ATECC608A_DEP_PLIB_I2C}
        children:
        - type: TargetAttachments
          children:
          - type: TargetAttachment
            attributes: {targetComponentID: i2c2, targetAttachmentID: I2C2_I2C}
- type: ElementPosition
  attributes: {x: '277', y: '277', id: atecc608a}
