format_version: v1.0
type: GeneratorComponent
attributes: {id: drv_memory}
children:
- type: Symbols
  children:
  - type: File
    attributes: {id: DRV_MEMORY_ASYNC_HEADER_LOCAL}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: DRV_MEMORY_ASYNC_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: DRV_MEMORY_COMMON_FS_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_memory, value: 'true'}
  - type: Combo
    attributes: {id: DRV_MEMORY_COMMON_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_memory, value: Synchronous}
      - type: User
        attributes: {value: Asynchronous}
  - type: Boolean
    attributes: {id: DRV_MEMORY_COMMON_SYS_TIME_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_memory, value: 'false'}
  - type: File
    attributes: {id: DRV_MEMORY_FS_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: DRV_MEMORY_SYNC_HEADER_LOCAL}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: DRV_MEMORY_SYNC_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
- type: Instances
  children:
  - type: InstanceComponent
    attributes: {instance: '0', id: drv_memory}
    children:
    - type: Symbols
      children:
      - type: Integer
        attributes: {id: DRV_MEMORY_BUFFER_QUEUE_SIZE}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: visible}
            children:
            - {type: Value, value: 'true'}
      - type: String
        attributes: {id: DRV_MEMORY_DEVICE}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_memory_0, value: DRV_SST26}
      - type: Comment
        attributes: {id: DRV_MEMORY_DEVICE_COMMENT}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: text}
            children:
            - {type: Value, value: '*** Configure Memory Device in DRV_SST26 Configurations
                ***'}
          - type: Boolean
            attributes: {id: visible}
            children:
            - {type: Value, value: 'true'}
      - type: Integer
        attributes: {id: DRV_MEMORY_DEVICE_POLL_US}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: visible}
            children:
            - {type: Value, value: 'false'}
      - type: Combo
        attributes: {id: DRV_MEMORY_DEVICE_TYPE}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: visible}
            children:
            - {type: Value, value: 'true'}
      - type: Boolean
        attributes: {id: DRV_MEMORY_ERASE_ENABLE}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_memory_0, value: 'true'}
      - type: Boolean
        attributes: {id: DRV_MEMORY_FS_ENABLE}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_memory_0, value: 'true'}
      - type: Boolean
        attributes: {id: DRV_MEMORY_INTERRUPT_ENABLE}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_memory_0, value: 'true'}
      - type: Integer
        attributes: {id: DRV_MEMORY_NUM_CLIENTS}
        children:
        - type: Values
          children:
          - type: User
            attributes: {value: '2'}
      - type: Menu
        attributes: {id: DRV_MEMORY_RTOS_MENU}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: visible}
            children:
            - {type: Value, value: 'true'}
      - type: File
        attributes: {id: DRV_MEMORY_SYS_RTOS_TASK}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: enabled}
            children:
            - {type: Value, value: 'true'}
    - type: Attachments
      children:
      - type: DirectDependency
        attributes: {id: drv_memory_MEMORY_dependency}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: targetComponentID}
            children:
            - {type: Value, value: drv_sst26}
          - type: String
            attributes: {id: targetAttachmentID}
            children:
            - {type: Value, value: memory}
- type: ElementPosition
  attributes: {x: '497', y: '265', id: drv_memory}
