format_version: v1.0
type: UniqueComponent
attributes: {id: i2c2}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: BRG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: i2c2, value: '992'}
  - type: Integer
    attributes: {id: I2CS_CORE_TIMER_FREQUENCY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: i2c2, value: '100000000'}
  - type: Integer
    attributes: {id: I2CS_RISE_TIME_CORE_TIMER_CNTS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: i2c2, value: '30'}
  - type: Integer
    attributes: {id: I2CS_SETUP_TIME_CORE_TIMER_CNTS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: i2c2, value: '10'}
  - type: Integer
    attributes: {id: I2C_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: i2c2, value: '100000000'}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: I2C2_I2C}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: atecc608a_0}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: ATECC608A_DEP_PLIB_I2C}
- type: ElementPosition
  attributes: {x: '134', y: '296', id: i2c2}
