format_version: v1.0
type: UniqueComponent
attributes: {id: sysMqttPic32mzw1}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: SYS_MQTT_APPDEBUG_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Menu
    attributes: {id: SYS_MQTT_APPDEBUG_FLOW_CONFIG_MENU}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: String
    attributes: {id: SYS_MQTT_APPDEBUG_PRESTR}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: String
    attributes: {id: SYS_MQTT_BROKER_NAME}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: a1gqt8sttiign3-ats.iot.us-east-2.amazonaws.com}
  - type: Boolean
    attributes: {id: SYS_MQTT_ENABLE_TLS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Integer
    attributes: {id: SYS_MQTT_KEEPALIVE_INTERVAL}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '30'}
  - type: Integer
    attributes: {id: SYS_MQTT_MQTT_PORT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '8883'}
- type: ElementPosition
  attributes: {x: '52', y: '421', id: sysMqttPic32mzw1}
