format_version: v1.0
type: UniqueComponent
attributes: {id: sysMqttPic32mzw1}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: SYS_MQTT_BROKER_NAME}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: a1gqt8sttiign3-ats.iot.us-east-2.amazonaws.com}
  - type: String
    attributes: {id: SYS_MQTT_CLIENT_ID}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: ''}
  - type: Boolean
    attributes: {id: SYS_MQTT_ENABLE_ALPN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: SYS_MQTT_ENABLE_SNI}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: SYS_MQTT_ENABLE_TLS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Integer
    attributes: {id: SYS_MQTT_MQTT_PORT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '443'}
- type: ElementPosition
  attributes: {x: '320', y: '20', id: sysMqttPic32mzw1}
