format_version: v1.0
type: UniqueComponent
attributes: {id: sysNetPic32mzw1}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: SYS_NET_ENABLE_TLS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sysMqttPic32mzw1, value: 'true'}
  - type: Boolean
    attributes: {id: SYS_NET_TNGTLS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
- type: ElementPosition
  attributes: {x: '332', y: '139', id: sysNetPic32mzw1}
