format_version: v1.0
type: UniqueComponent
attributes: {id: tcpipTcp}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: TCPIP_TCP_HEAP_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipTcp, value: '74320'}
  - type: Integer
    attributes: {id: TCPIP_TCP_SOCKET_DEFAULT_RX_SIZE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '5840'}
  - type: Integer
    attributes: {id: TCPIP_TCP_SOCKET_DEFAULT_TX_SIZE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1460'}
- type: ElementPosition
  attributes: {x: '440', y: '20', id: tcpipTcp}
